name: Android CI
# sample
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SECRET_PLAY_STORE_JSON }}
          packageName: com.carnagestudios.paddyp
          releaseFiles: app/release/app-release.aab
          track: alpha
